#!/usr/bin/env bash
# Wait for the running 32B int8 fit, then run the 32B analyses and regenerate the
# scale figures. Everything here is forward-only (the fit is already done), so no
# OOM risk once the fit frees the GPU.
#
# NB: do not edit this file while it is running -- bash reads scripts by byte
# offset, so an edit under a live interpreter can execute garbage. Kill it first.
set -uo pipefail
cd "$(dirname "$0")/.."
export HF_HOME="$PWD/models"
PY="$PWD/.venv/bin/python"
LOG=out/after32b.log
mark() { echo "[$(date +%H:%M:%S)] $*" | tee -a "$LOG"; }
run() { mark "RUN $*"; "$PY" "$@" 2>>"$LOG" | tee -a "$LOG" || mark "  (failed: $*)"; }
: > "$LOG"

mark "waiting for 32B int8 fit to finish ..."
while pgrep -f "fit_lens.py 32b" >/dev/null; do sleep 60; done
[ -f out/lenses/32b-int8.pt ] || { mark "ERROR: 32b-int8.pt not found"; exit 1; }
mark "32B lens present: $(stat -c %s out/lenses/32b-int8.pt) bytes"

# core scale + causal
run scripts/metrics.py     32b --int8
run scripts/lens_eval.py   32b --int8 --limit 40
run scripts/causal_swap.py 32b --int8

# J-lens vs logit-lens concept-plane trajectory (both paths pass through the
# final norm, so the contrast is not a magnitude artifact)
run scripts/flow.py 32b --int8 --intermediate Italy --answer euro

run scripts/plots.py
mark "=== 32B ANALYSES COMPLETE ==="
